[package]
name = "denju"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
clap.workspace = true
denju-client = { path = "../../crates/denju-client" }
denju-core = { path = "../../crates/denju-core" }
denju-local = { path = "../../crates/denju-local" }
denju-sync = { path = "../../crates/denju-sync" }
denju-wire = { path = "../../crates/denju-wire" }
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
url.workspace = true
uuid.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
